In [ ]:
import torch

torch.cuda.is_available(), torch.cuda.device_count(), torch.cuda.get_device_name()

(True, 8, 'NVIDIA A100-SXM4-40GB')

In [10]:
x = torch.arange(12)
print(f'x = {x}')
print(f'shape: {x.shape}, num of elements: {x.numel()}')

x = tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
shape: torch.Size([12]), num of elements: 12


In [11]:
X = x.reshape(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
tensor_zeros = torch.zeros(2, 3, 4)
tensor_zeros.shape

torch.Size([2, 3, 4])

In [14]:
tensor_ones = torch.ones(3, 4, 5)
tensor_ones.numel()

60

In [15]:
tensor_random = torch.randn(4, 5, 6)
tensor_random

tensor([[[-0.8668,  0.3133, -0.7083, -1.0915,  1.7692, -0.0696],
         [-0.3144,  0.6706, -0.1394,  1.4802, -2.0274, -0.3041],
         [ 0.7882,  0.9518, -1.1819,  2.0045,  1.7796, -0.7668],
         [-0.3985,  1.1675,  0.0167, -0.8373,  1.0315,  1.5213],
         [ 0.5127, -0.2914, -0.4879, -0.5390,  0.1274,  0.7984]],

        [[-0.2939,  0.7920, -2.0695, -0.0473, -0.9741, -0.0580],
         [-1.4119, -0.0606, -0.2085,  0.6485, -1.1731, -0.7628],
         [ 1.0099,  0.3410,  0.1087,  0.1323, -0.6420, -0.9774],
         [-0.5187,  0.0078, -0.0542,  1.4988,  1.3693, -0.4816],
         [ 1.4543, -1.2108, -0.3697, -0.4524, -0.4081,  0.9063]],

        [[-0.9266,  0.7334,  1.0624, -0.5593,  1.1643,  0.5166],
         [-1.2162, -1.9906,  0.6023, -0.3976, -0.3003, -0.0538],
         [-0.1678,  1.8837,  0.9417, -0.8028, -0.3480, -2.0655],
         [-1.4149, -0.7537, -0.3634,  1.5593,  0.8026,  0.8918],
         [-0.1824, -1.5585,  0.3028,  1.4039, -0.5078,  0.9163]],

        [[-0.3146, 

In [16]:
torch.tensor([[1,2,3,4], [2,3,4,5], [3,4,5,6]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

In [17]:
A = torch.tensor([9,8,7,6,5])
B = torch.tensor([1,2,3,4,5])

A+B, A-B, A*B, A/B, A**B

(tensor([10, 10, 10, 10, 10]),
 tensor([8, 6, 4, 2, 0]),
 tensor([ 9, 16, 21, 24, 25]),
 tensor([9.0000, 4.0000, 2.3333, 1.5000, 1.0000]),
 tensor([   9,   64,  343, 1296, 3125]))

In [18]:
torch.exp(B)

tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])

In [19]:
A = torch.arange(12, dtype=torch.float16).reshape(-1,4)
B = torch.tensor([[2., 1, 4, 3], [4, 3, 2, 1], [2, 4, 6, 8]])
torch.cat((A, B), dim=0), torch.cat([B, A], dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 4.,  3.,  2.,  1.],
         [ 2.,  4.,  6.,  8.]]),
 tensor([[ 2.,  1.,  4.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  3.,  2.,  1.,  4.,  5.,  6.,  7.],
         [ 2.,  4.,  6.,  8.,  8.,  9., 10., 11.]]))

In [20]:
A == B

tensor([[False,  True, False,  True],
        [ True, False, False, False],
        [False, False, False, False]])

In [21]:
A.sum(), B.sum()

(tensor(66., dtype=torch.float16), tensor(40.))

In [22]:
A[-1], A[1:3], B[2, 3]

(tensor([ 8.,  9., 10., 11.], dtype=torch.float16),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]], dtype=torch.float16),
 tensor(8.))

In [23]:
A[0:2, :] = 8
A

tensor([[ 8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.],
        [ 8.,  9., 10., 11.]], dtype=torch.float16)

In [24]:
tmp_id = id(B)
B = B + A
id(B) == tmp_id

False

In [25]:
Z = torch.zeros_like(A)
print('id(Z)', id(Z))
Z[:] = A + B
print('id(Z)', id(Z))
Z

id(Z) 47162937079712
id(Z) 47162937079712


tensor([[18., 17., 20., 19.],
        [20., 19., 18., 17.],
        [18., 22., 26., 30.]], dtype=torch.float16)