In [17]:
import torch

torch.cuda.is_available(), torch.cuda.device_count(), torch.cuda.get_device_name()

(True, 1, 'NVIDIA GeForce RTX 3080')

In [2]:
x = torch.arange(12)
print(f'x = {x}')
print(f'shape: {x.shape}, num of elements: {x.numel()}')

x = tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
shape: torch.Size([12]), num of elements: 12


In [3]:
X = x.reshape(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
tensor_zeros = torch.zeros(2, 3, 4)
tensor_zeros.shape

torch.Size([2, 3, 4])

In [5]:
tensor_ones = torch.ones(3, 4, 5)
tensor_ones.numel()

60

In [6]:
tensor_random = torch.randn(4, 5, 6)
tensor_random

tensor([[[ 1.2692, -0.1161, -0.5972,  0.3669, -2.2151,  1.4756],
         [ 0.0052,  0.6107,  1.2069, -0.4424, -2.1285, -0.5558],
         [-0.3272, -1.3648, -0.4518, -0.1837,  0.9852, -0.7316],
         [ 0.6751, -0.8946,  0.7669, -0.4268, -0.6006, -0.1154],
         [ 0.0557,  0.6747, -0.6773,  1.3574, -0.4657, -1.6515]],

        [[-2.6675, -0.2066,  1.5217, -1.3404,  2.1560,  1.2240],
         [-0.8512, -0.9044, -0.4417, -0.2336, -0.6772,  0.1564],
         [-0.0374,  0.3611,  1.3258,  0.2373,  0.5034, -0.5522],
         [-0.2589, -1.2037,  0.4529,  1.2758, -1.3871, -0.1162],
         [ 1.4637,  1.1759, -0.1978, -1.0936, -1.3542, -0.6562]],

        [[-1.2751, -1.1504, -0.5180, -0.3412,  0.4227,  0.4797],
         [ 0.8273,  1.4262, -0.0059, -1.5180, -0.1454, -0.0459],
         [ 0.7009, -0.4269,  0.3030, -0.3018, -1.2005,  1.2384],
         [-0.5311, -1.6729, -0.4870, -1.0219, -0.7827, -0.3818],
         [ 0.2161,  1.8885,  0.3840,  1.0894,  0.3124, -0.1954]],

        [[ 1.2814, 

In [7]:
torch.tensor([[1,2,3,4], [2,3,4,5], [3,4,5,6]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

In [8]:
A = torch.tensor([9,8,7,6,5])
B = torch.tensor([1,2,3,4,5])

A+B, A-B, A*B, A/B, A**B

(tensor([10, 10, 10, 10, 10]),
 tensor([8, 6, 4, 2, 0]),
 tensor([ 9, 16, 21, 24, 25]),
 tensor([9.0000, 4.0000, 2.3333, 1.5000, 1.0000]),
 tensor([   9,   64,  343, 1296, 3125]))

In [9]:
torch.exp(B)

tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])

In [10]:
A = torch.arange(12, dtype=torch.float16).reshape(-1,4)
B = torch.tensor([[2., 1, 4, 3], [4, 3, 2, 1], [2, 4, 6, 8]])
torch.cat((A, B), dim=0), torch.cat([B, A], dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 4.,  3.,  2.,  1.],
         [ 2.,  4.,  6.,  8.]]),
 tensor([[ 2.,  1.,  4.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  3.,  2.,  1.,  4.,  5.,  6.,  7.],
         [ 2.,  4.,  6.,  8.,  8.,  9., 10., 11.]]))

In [11]:
A == B

tensor([[False,  True, False,  True],
        [ True, False, False, False],
        [False, False, False, False]])

In [12]:
A.sum(), B.sum()

(tensor(66., dtype=torch.float16), tensor(40.))

In [13]:
A[-1], A[1:3], B[2, 3]

(tensor([ 8.,  9., 10., 11.], dtype=torch.float16),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]], dtype=torch.float16),
 tensor(8.))

In [14]:
A[0:2, :] = 8
A

tensor([[ 8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.],
        [ 8.,  9., 10., 11.]], dtype=torch.float16)

In [15]:
tmp_id = id(B)
B = B + A
id(B) == tmp_id

False

In [16]:
Z = torch.zeros_like(A)
print('id(Z)', id(Z))
Z[:] = A + B
print('id(Z)', id(Z))
Z

id(Z) 139874435379472
id(Z) 139874435379472


tensor([[18., 17., 20., 19.],
        [20., 19., 18., 17.],
        [18., 22., 26., 30.]], dtype=torch.float16)