In [1]:
import torch

x = torch.tensor(3.)
y = torch.tensor(2.)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
#x = torch.tensor([0,1,2,3])
x = torch.arange(4)
x, x[2]

(tensor([0, 1, 2, 3]), tensor(2))

In [3]:
len(x), x.shape

(4, torch.Size([4]))

In [4]:
A = torch.arange(20).reshape(5,-1)
A, A.T, A[2,:], A[2], A.T[3,4]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([ 8,  9, 10, 11]),
 tensor([ 8,  9, 10, 11]),
 tensor(19))

In [5]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B, B==B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [6]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(60, dtype=torch.float16).reshape(-1,5,4)
B = A[1].clone()
A, A + B

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]],
 
         [[40., 41., 42., 43.],
          [44., 45., 46., 47.],
          [48., 49., 50., 51.],
          [52., 53., 54., 55.],
          [56., 57., 58., 59.]]], dtype=torch.float16),
 tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]],
 
         [[40., 42., 44., 46.],
          [48., 50., 52., 54.],
          [56., 58., 60., 62.],
          [64., 66., 68., 70.],
          [72., 74., 76., 78.]],
 
         [[60., 62., 64., 66.],
          [68., 70., 72., 74.],
          [76., 78., 80., 82.],
          [84., 86., 88., 90.],
          [92., 94., 96., 98.]]], dt

In [13]:
A * B

tensor([[[   0.,   21.,   44.,   69.],
         [  96.,  125.,  156.,  189.],
         [ 224.,  261.,  300.,  341.],
         [ 384.,  429.,  476.,  525.],
         [ 576.,  629.,  684.,  741.]],

        [[ 400.,  441.,  484.,  529.],
         [ 576.,  625.,  676.,  729.],
         [ 784.,  841.,  900.,  961.],
         [1024., 1089., 1156., 1225.],
         [1296., 1369., 1444., 1521.]],

        [[ 800.,  861.,  924.,  989.],
         [1056., 1125., 1196., 1269.],
         [1344., 1421., 1500., 1581.],
         [1664., 1749., 1836., 1925.],
         [2016., 2108., 2204., 2300.]]], dtype=torch.float16)

In [15]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, a * X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [18]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [20]:
A.shape, A.sum()

(torch.Size([3, 5, 4]), tensor(1770., dtype=torch.float16))

In [29]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis12 = A.sum(axis=(1,2))
A_sum_axis0, A_sum_axis0.shape, A_sum_axis12, A_sum_axis12.shape

(tensor([[ 60.,  63.,  66.,  69.],
         [ 72.,  75.,  78.,  81.],
         [ 84.,  87.,  90.,  93.],
         [ 96.,  99., 102., 105.],
         [108., 111., 114., 117.]], dtype=torch.float16),
 torch.Size([5, 4]),
 tensor([190., 590., 990.], dtype=torch.float16),
 torch.Size([3]))

In [31]:
A.mean(), A.sum() / A.numel()

(tensor(29.5000, dtype=torch.float16), tensor(29.5000, dtype=torch.float16))

In [33]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]], dtype=torch.float16),
 tensor([[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]], dtype=torch.float16))

In [41]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, A / sum_A

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]],
 
         [[240., 245., 250., 255.]]], dtype=torch.float16),
 tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
          [0.1000, 0.1111, 0.1200, 0.1273],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.3000, 0.2888, 0.2800, 0.2727],
          [0.3999, 0.3777, 0.3601, 0.3455]],
 
         [[0.1428, 0.1448, 0.1466, 0.1484],
          [0.1714, 0.1724, 0.1733, 0.1742],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2285, 0.2275, 0.2267, 0.2258],
          [0.2571, 0.2551, 0.2534, 0.2517]],
 
         [[0.1666, 0.1674, 0.1680, 0.1686],
          [0.1833, 0.1837, 0.1840, 0.1843],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2167, 0.2163, 0.2159, 0.2157],
          [0.2333, 0.2327, 0.2321, 0.2313]]], dtype=torch.float16))

In [73]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [90]:
A = A.float()

A[0].shape, x.shape, torch.mv(A[0],x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [93]:
B = torch.ones(4,3)
A[0], B, torch.mm(A[0],B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [95]:
u = torch.tensor([3., -4])
u, torch.norm(u)

(tensor([ 3., -4.]), tensor(5.))

In [97]:
torch.abs(u), torch.abs(u).sum()

(tensor([3., 4.]), tensor(7.))

In [112]:
torch.norm(torch.ones(4,9))

tensor(6.)